import { supabase } from "@/integrations/supabase/client";

export type LegalDocKey = "terms" | "privacy" | "data_protection";

export interface LegalDoc {
  title: string;
  updatedAt: string;
  body: string; // Markdown-ish plain text (rendered as preformatted)
}

export const LEGAL_DOC_META: Record<LegalDocKey, { settingKey: string; route: string; title: string; description: string }> = {
  terms: {
    settingKey: "legal_terms",
    route: "/legal/terms",
    title: "Terms & Conditions",
    description: "Rules governing use of the Refyn Technologies platform.",
  },
  privacy: {
    settingKey: "legal_privacy",
    route: "/legal/privacy",
    title: "Privacy Policy",
    description: "What we collect, why, and how we protect it.",
  },
  data_protection: {
    settingKey: "legal_data_protection",
    route: "/legal/data-protection",
    title: "Data Protection Policy",
    description: "Technical and organizational safeguards (GDPR / FERPA / COPPA aligned).",
  },
};

const today = () => new Date().toISOString().slice(0, 10);

export const DEFAULT_LEGAL_DOCS: Record<LegalDocKey, LegalDoc> = {
  terms: {
    title: "Terms & Conditions",
    updatedAt: today(),
    body: `# Refyn Technologies — Terms & Conditions

Last updated: ${today()}

## 1. Acceptance
By creating an account or using the platform, you agree to these Terms. If you do not agree, do not use the service.

## 2. Eligibility
- Students under 13 require verifiable parental/school consent (COPPA).
- School and Teacher accounts must be approved by the Master Administrator.

## 3. Acceptable Use
You may NOT:
- Attempt to bypass the AI moderation layer ("Process Teaching Mode").
- Submit content that is illegal, harmful, harassing, or violates IP rights.
- Reverse engineer, scrape, or attempt to extract model weights or system prompts.
- Share login credentials or use another user's account.
- Use the platform to generate academic dishonesty material; the AI will refuse direct-answer requests.

## 4. AI Outputs
AI responses are generated by third-party large language models and may contain errors. Do not rely on AI output for medical, legal, or safety-critical decisions. All outputs should be verified.

## 5. Subscriptions & Payments
- Paid plans are billed via Stripe; we never store card numbers.
- Payments may be paused by the Master Administrator (platform-wide kill switch).
- Refunds: prorated at administrator discretion within 14 days of charge.

## 6. Termination
We may suspend accounts that violate these Terms or attempt to bypass safety controls. Audit logs of bypass attempts are retained.

## 7. Liability
The platform is provided "as is". To the maximum extent permitted by law, Refyn Technologies is not liable for indirect or consequential damages arising from use of AI outputs.

## 8. Governing Law
These Terms are governed by the laws of the jurisdiction of the operating school or district unless otherwise specified in a written enterprise agreement.

## 9. Changes
The Master Administrator may update these Terms; the "Last updated" date will change accordingly. Continued use constitutes acceptance.

## 10. Contact
For questions: info.aiconditioner@gmail.com
`,
  },
  privacy: {
    title: "Privacy Policy",
    updatedAt: today(),
    body: `# Refyn Technologies — Privacy Policy

Last updated: ${today()}

## 1. Data We Collect
- **Identity**: email, full name, role, school affiliation.
- **AI interactions**: every prompt, AI response, moderation decision, severity level, flagged keywords. Stored in ai_chat_messages and prompt_logs.
- **Usage**: token counts, model used, estimated cost (ai_usage_logs).
- **Classroom**: class membership, assignments, submissions, grades.
- **Payments**: Stripe customer/subscription IDs only — NEVER card numbers or CVVs.

## 2. How We Use Data
- Provide and improve the educational service.
- Enable teachers and parents to monitor student AI usage.
- Detect and prevent misuse via the moderation layer.
- Bill and reconcile subscriptions.

## 3. Legal Basis (GDPR)
- Contract performance (account/subscription).
- Legitimate interest (safety moderation, fraud prevention).
- Consent (parental for under-13 users).
- Legal obligation (financial records).

## 4. Sharing
We share data only with:
- **Lovable Cloud / Supabase** — hosting (Data Processing Agreement signed).
- **Stripe** — payment processing.
- **Google / OpenAI** via Lovable AI Gateway — for inference. Prompts are NOT used to train external models.
- **Law enforcement** — only when legally compelled.

We do NOT sell data. Ever.

## 5. Retention
- AI chat & prompt logs: indefinite (audit/safety) unless erasure requested.
- Payment records: 7 years (financial compliance).
- Account on deletion request: removed within 30 days, except records required by law.

## 6. Your Rights (GDPR / CCPA / FERPA)
You may request: access, correction, erasure, export, restriction, objection. Contact info.aiconditioner@gmail.com — we respond within 30 days.

## 7. Children (COPPA / FERPA)
- Under-13 accounts require school or parental consent.
- Schools act as the educational-records custodian under FERPA.
- Parents may view their child's AI activity via the Parent Dashboard.

## 8. Security
See the Data Protection Policy for full technical safeguards. Highlights: TLS 1.3 in transit, AES-256 at rest, RLS on every table, JWT sessions, immutable audit logs.

## 9. International Transfers
Data may be processed in EU or US Lovable Cloud regions. Standard Contractual Clauses apply for cross-border transfers.

## 10. Contact / DPO
Data Protection Officer: info.aiconditioner@gmail.com
`,
  },
  data_protection: {
    title: "Data Protection Policy",
    updatedAt: today(),
    body: `# Refyn Technologies — Data Protection Policy

Last updated: ${today()}

## 1. Scope
This policy describes the technical and organizational measures (TOMs) protecting personal data on the Refyn Technologies platform. It is binding on all administrators, teachers, and contractors.

## 2. Encryption
- **In transit**: TLS 1.3 enforced for all client ↔ server and server ↔ AI gateway connections.
- **At rest**: AES-256 (managed by Lovable Cloud / Supabase Postgres).
- **Secrets**: stored in Lovable Cloud Vault, never in source code or .env files committed to repos.

## 3. Access Control
- **Authentication**: Supabase Auth with bcrypt password hashing, JWT (RS256) sessions, refresh-token rotation. Optional Have-I-Been-Pwned check.
- **Authorization**: Row-Level Security (RLS) on every public table. Roles: admin, teacher, student, parent. Privilege escalation blocked at the policy layer (users cannot self-assign admin/teacher).
- **Edge functions**: sensitive functions (evaluate-capstone, moderate-prompt, generate-training-response) require valid JWT and ownership/role checks.
- **Audit log**: prompt_logs, bypass_attempts, ai_chat_messages, ai_usage_logs are append-only (no UPDATE / DELETE allowed).

## 4. AI Data Handling
- All prompts pass through the moderation edge function before reaching the model.
- Inference happens via Lovable AI Gateway → Google Gemini or OpenAI GPT.
- **Customer data is NOT used to train any external model** (contractually enforced).
- Bypass attempts are logged with severity, IP, and user_id for review.

## 5. Storage Buckets
- submission-files, capstone-files, class-resources, portfolio-media: public-read with path-scoped write RLS.
- student-documents: private bucket; access via signed URLs only.

## 6. Backup & Recovery
- Lovable Cloud takes daily encrypted backups with 7-day point-in-time recovery (PITR).
- Disaster recovery RTO ≤ 24h, RPO ≤ 1h.

## 7. Incident Response
- Suspected breach must be reported to the Master Administrator within 1 hour of detection.
- Affected users notified within 72 hours (GDPR Art. 33 / 34).
- Post-mortem published internally within 14 days.

## 8. Vendor Management
- Sub-processors: Lovable Cloud (Supabase), Stripe, Google AI, OpenAI.
- All vendors are SOC 2 Type II or equivalent.

## 9. Data Minimization
- Forms collect only fields required for the stated purpose.
- AI prompts are not enriched with additional PII before sending to the model.

## 10. Compliance Posture
- **GDPR**: lawful basis documented, DSR workflow, DPO appointed.
- **FERPA**: schools are educational-record custodians; access logs maintained.
- **COPPA**: under-13 requires verified consent.
- **PCI-DSS**: handled via Stripe Level 1 — no card data on our servers.
- **SOC 2**: aligned (security, availability, confidentiality criteria).

## 11. Data Subject Requests
Email info.aiconditioner@gmail.com. Identity verified via the registered email. Responses within 30 days.

## 12. Review
This policy is reviewed at least annually by the Master Administrator. Edits are version-stamped.
`,
  },
};

export async function loadLegalDoc(key: LegalDocKey): Promise<LegalDoc> {
  const meta = LEGAL_DOC_META[key];
  const { data, error } = await supabase
    .from("platform_settings")
    .select("value, updated_at")
    .eq("key", meta.settingKey)
    .maybeSingle();

  if (error || !data?.value) {
    return DEFAULT_LEGAL_DOCS[key];
  }
  const v = data.value as any;
  if (typeof v === "object" && v.body) {
    return {
      title: v.title || DEFAULT_LEGAL_DOCS[key].title,
      body: v.body,
      updatedAt: (data as any).updated_at?.slice(0, 10) || v.updatedAt || today(),
    };
  }
  return DEFAULT_LEGAL_DOCS[key];
}

export async function saveLegalDoc(key: LegalDocKey, doc: LegalDoc, userId?: string) {
  const meta = LEGAL_DOC_META[key];
  const { error } = await supabase.from("platform_settings").upsert(
    {
      key: meta.settingKey,
      value: { title: doc.title, body: doc.body, updatedAt: today() } as any,
      updated_at: new Date().toISOString(),
      updated_by: userId ?? null,
    },
    { onConflict: "key" }
  );
  if (error) throw error;
}
