// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/my-classes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
var env = (name) => {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
};
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Sign in required");
  const url = env("SUPABASE_URL") ?? env("VITE_SUPABASE_URL");
  const keyset = env("SUPABASE_PUBLISHABLE_KEYS");
  let publishable;
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        publishable = Object.values(parsed).find((v) => typeof v === "string" && v.startsWith("sb_publishable_"));
      }
    } catch {
    }
  }
  const key = env("SUPABASE_PUBLISHABLE_KEY") ?? env("VITE_SUPABASE_PUBLISHABLE_KEY") ?? publishable ?? env("SUPABASE_ANON_KEY");
  if (!url || !key) throw new Error("Data connection unavailable");
  return createClient(url, key, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false, autoRefreshToken: false } });
}

// src/lib/mcp/tools/my-classes.ts
var my_classes_default = defineTool({
  name: "list_my_classes",
  title: "My classes",
  description: "List the signed-in person's classes, with their subject and curriculum.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Sign in required." }], isError: true };
    const db = supabaseForUser(ctx);
    const { data: membership, error: membershipError } = await db.from("class_members").select("class_id").eq("student_id", ctx.getUserId()).limit(100);
    if (membershipError) throw new Error(membershipError.message);
    const ids = (membership ?? []).map((row) => row.class_id);
    const { data: taught, error: taughtError } = await db.from("classes").select("id, name, subject, curriculum_type").eq("teacher_id", ctx.getUserId()).limit(100);
    if (taughtError) throw new Error(taughtError.message);
    const { data: enrolled, error: enrolledError } = ids.length ? await db.from("classes").select("id, name, subject, curriculum_type").in("id", ids).limit(100) : { data: [], error: null };
    if (enrolledError) throw new Error(enrolledError.message);
    const classes = [...(taught ?? []).map((row) => ({ ...row, relationship: "teacher" })), ...(enrolled ?? []).filter((row) => !(taught ?? []).some((item) => item.id === row.id)).map((row) => ({ ...row, relationship: "student" }))];
    return { content: [{ type: "text", text: JSON.stringify(classes) }], structuredContent: { classes } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kvblawqwgjoibzkunhqv";
var mcp_default = defineMcp({
  name: "refyn-dashboard-v1",
  title: "REFYN DASHBOARD v1",
  version: "0.1.0",
  instructions: "Access the signed-in person's Refyn classes. Follow their existing permissions.",
  auth: auth.oauth.issuer({ issuer: `https://${projectRef}.supabase.co/auth/v1`, acceptedAudiences: "authenticated" }),
  tools: [my_classes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
